### PR TITLE
📝Cleanup documentation

### PR DESCRIPTION
**Pull request by 0xClandestine**
First of all, my bad, I should have created an issue first. Nonetheless, feel free to close this PR.

TODO:
- fix readme links to work with 0xKitsune repo (only a few)

### CODE REVIEW

**Comment by 0xKitsune** [comment]
Wow this looks way cleaner, thank you for the PR! I recently pushed some updates, can you resolve the merge conflicts with the Contributing.md file? After that I can merge this into development and then to main.

**Comment by 0xClandestine** [comment]
> Wow this looks way cleaner, thank you for the PR! I recently pushed some updates, can you resolve the merge conflicts with the Contributing.md file? After that I can merge this into development and then to main.

Yeah I can take care of it, thanks :)

**Comment by 0xClandestine** [comment]
Kinda odd, I cannot see the conflicts locally and I'm honestly not very familiar with git cli, would you mind fixing the conflicts?

I would still need to fix the links.

**Comment by 0xClandestine** [comment]
@0xKitsune

**Comment by 0xKitsune** [comment]
@0xClandestine I pulled the changes locally and fixed the merge conflicts. [Moving to a new PR here, with your changes](#21 ).

**Pull request closed without merging**
