### PR TITLE
feat: add divide before multiply vulnerability

### LINKED ISSUE #44: Vulnerability Request: Divide before multiply
Match when division is used before multiplication.

[Details from slither](https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply)

### PR DESCRIPTION
**Pull request by 0xble**
Closes #44

### CODE REVIEW

**Comment by 0xKitsune** [comment]
Hey thanks for the PR! I'll take a look at everything now.

**Comment by 0xKitsune** [comment]
@0xble Great work, the PR looks really clean. I added two quick comments. Once everything is updated, I can merge this in! Let me know if you have any questions or if I can provide any further clarity.

**Comment by 0xble** [comment]
> @0xble Great work, the PR looks really clean. I added two quick comments. Once everything is updated, I can merge this in! Let me know if you have any questions or if I can provide any further clarity.

Thanks for the feedback! Sorry, I can't seem to find those comments. Could you point me to where they are?

**Comment by 0xKitsune** [comment]
> Thanks for the feedback! Sorry, I can't seem to find those comments. Could you point me to where they are?

No problem, I just tagged you in the review. It is right above your comment in this thread.

**Comment by 0xble** [comment]
> > Thanks for the feedback! Sorry, I can't seem to find those comments. Could you point me to where they are?
> 
> No problem, I just tagged you in the review. It is right above your comment in this thread.

Huh weird, for some reason I don't see the thread 😅 This is all that shows up for me above the comment:

image

**Review by 0xKitsune — CHANGES_REQUESTED** [review]

**Comment by 0xKitsune** [comment]
> Huh weird, for some reason I don't see the thread sweat_smile This is all that shows up for me above the comment:

Whoops, looks like I didn't publish the review. Sorry for the confusion, it should be visible now. If not let me know.

**Comment by 0xKitsune** [comment]
Sorry for the delay on this, its been pretty busy recently. Ill be prioritizing merging PRs within solstat and pushing some of the features outline in the issues this week.

**Comment by 0xble** [comment]
> Sorry for the delay on this, its been pretty busy recently. Ill be prioritizing merging PRs within solstat and pushing some of the features outline in the issues this week.

No worries!

**Pull request merged**
