### PR TITLE
feat: --match-file-name command

### PR DESCRIPTION
**Pull request by 0xClandestine**
Introduces `--match-file-name` command which allows users to generate a report for a specific contract within path.

### Usage
```js
solstat --match-file-name "Contract.sol"
```

### CODE REVIEW

**Comment by 0xClandestine** [comment]
Currently learning rust, forgive any messy-ness 🙏

**Comment by 0xKitsune** [comment]
No time to learn Rust like the present.

I like the idea of being able to run solstat on a single file. You can actually make this much more simplified. 

Instead of passing down `opts.match_file_name` after running analysis on all of the directories in the path, you can just check if the `opt.match_file_name.is_some()` and then pass that in instead of the `os.path`.

So instead of this:

```rust
fn main() {
    let opts = Opts::new();

    let vulnerabilities = vulnerabilities::analyze_dir(&opts.path, opts.vulnerabilities);
    let optimizations = optimizations::analyze_dir(&opts.path, opts.optimizations);
    let qa = qa::analyze_dir(&opts.path, opts.qa);
    
    generate_report(vulnerabilities, optimizations, qa, opts.match_file_name);
}
```

You can do something like this:

```rust
fn main() {
    let opts = Opts::new();

    let path = match opts.match_file_name.is_some() {
        Some(file_path) => file_path,
        None => ops.path,
    }

    let vulnerabilities = vulnerabilities::analyze_dir(&path, opts.vulnerabilities);
    let optimizations = optimizations::analyze_dir(&path, opts.optimizations);
    let qa = qa::analyze_dir(&path, opts.qa);
    
    generate_report(vulnerabilities, optimizations, qa);
}
```
This way you can add the feature without changing any of the core codebase (other than the opts mod).

**Comment by 0xClandestine** [comment]
> No time to learn Rust like the present.
> 
> I like the idea of being able to run solstat on a single file. You can actually make this much more simplified.
> 
> Instead of passing down `opts.match_file_name` after running analysis on all of the directories in the path, you can just check if the `opt.match_file_name.is_some()` and if so, pass that in to the `analyze_dir()` functions instead of the `os.path`. Ill probably end up renaming the `analyze_dir()` function to just `analyze_source()` or something more generic anyway.
> 
> So instead of this:
> 
> ```rust
> fn main() {
>     let opts = Opts::new();
> 
>     let vulnerabilities = vulnerabilities::analyze_dir(&opts.path, opts.vulnerabilities);
>     let optimizations = optimizations::analyze_dir(&opts.path, opts.optimizations);
>     let qa = qa::analyze_dir(&opts.path, opts.qa);
>     
>     generate_report(vulnerabilities, optimizations, qa, opts.match_file_name);
> }
> ```
> 
> You can do something like this:
> 
> ```rust
> fn main() {
>     let opts = Opts::new();
> 
>     let path = match opts.match_file_name.is_some() {
>         Some(file_path) => file_path,
>         None => ops.path,
>     }
> 
>     let vulnerabilities = vulnerabilities::analyze_dir(&path, opts.vulnerabilities);
>     let optimizations = optimizations::analyze_dir(&path, opts.optimizations);
>     let qa = qa::analyze_dir(&path, opts.qa);
>     
>     generate_report(vulnerabilities, optimizations, qa);
> }
> ```
> 
> This way you can add the feature without changing any of the core codebase (other than the opts mod).

Oh yeah that's much simpler haha, tbh this was my first rust contribution. Anyways thanks for the detailed reply, ended up learning something :)

**Comment by 0xClandestine** [comment]
Going to close this PR, will create another with your suggested changes.

**Pull request closed without merging**
